SET FOREIGN_KEY_CHECKS=0;

CREATE TABLE `example` (
  `EXAMPLE_ID` varchar(20) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci NOT NULL,
  `EXAMPLE_TYPE_ID` varchar(20) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci DEFAULT NULL,
  `STATUS_ID` varchar(20) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci DEFAULT NULL,
  `EXAMPLE_NAME` varchar(100) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci DEFAULT NULL,
  `DESCRIPTION` varchar(255) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci DEFAULT NULL,
  `LONG_DESCRIPTION` longtext CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci,
  `COMMENTS` varchar(255) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci DEFAULT NULL,
  `EXAMPLE_SIZE` decimal(20,0) DEFAULT NULL,
  `EXAMPLE_DATE` datetime(3) DEFAULT NULL,
  `ANOTHER_DATE` datetime(3) DEFAULT NULL,
  `ANOTHER_TEXT` varchar(255) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci DEFAULT NULL,
  `LAST_UPDATED_STAMP` datetime(3) DEFAULT NULL,
  `LAST_UPDATED_TX_STAMP` datetime(3) DEFAULT NULL,
  `CREATED_STAMP` datetime(3) DEFAULT NULL,
  `CREATED_TX_STAMP` datetime(3) DEFAULT NULL,
  PRIMARY KEY (`EXAMPLE_ID`),
  KEY `EXMPL_TYP` (`EXAMPLE_TYPE_ID`),
  KEY `EXMPL_STTS` (`STATUS_ID`),
  KEY `EXAMPLE_TXSTMP` (`LAST_UPDATED_TX_STAMP`),
  KEY `EXAMPLE_TXCRTS` (`CREATED_TX_STAMP`),
  CONSTRAINT `EXMPL_STTS` FOREIGN KEY (`STATUS_ID`) REFERENCES `status_item` (`STATUS_ID`),
  CONSTRAINT `EXMPL_TYP` FOREIGN KEY (`EXAMPLE_TYPE_ID`) REFERENCES `example_type` (`EXAMPLE_TYPE_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3;

CREATE TABLE `example_item` (
  `EXAMPLE_ID` varchar(20) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci NOT NULL,
  `EXAMPLE_ITEM_SEQ_ID` varchar(20) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci NOT NULL,
  `DESCRIPTION` varchar(255) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci DEFAULT NULL,
  `AMOUNT` double DEFAULT NULL,
  `AMOUNT_UOM_ID` varchar(20) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci DEFAULT NULL,
  `LAST_UPDATED_STAMP` datetime(3) DEFAULT NULL,
  `LAST_UPDATED_TX_STAMP` datetime(3) DEFAULT NULL,
  `CREATED_STAMP` datetime(3) DEFAULT NULL,
  `CREATED_TX_STAMP` datetime(3) DEFAULT NULL,
  PRIMARY KEY (`EXAMPLE_ID`,`EXAMPLE_ITEM_SEQ_ID`),
  KEY `EXMPLIT_UOM` (`AMOUNT_UOM_ID`),
  KEY `EXMPLIT_EXMP` (`EXAMPLE_ID`),
  KEY `EXMPL_ITM_TXSTMP` (`LAST_UPDATED_TX_STAMP`),
  KEY `EXMPL_ITM_TXCRTS` (`CREATED_TX_STAMP`),
  CONSTRAINT `EXMPLIT_EXMP` FOREIGN KEY (`EXAMPLE_ID`) REFERENCES `example` (`EXAMPLE_ID`),
  CONSTRAINT `EXMPLIT_UOM` FOREIGN KEY (`AMOUNT_UOM_ID`) REFERENCES `uom` (`UOM_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3;

CREATE TABLE `example_status` (
  `EXAMPLE_ID` varchar(20) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci NOT NULL,
  `STATUS_DATE` datetime(3) NOT NULL,
  `STATUS_END_DATE` datetime(3) DEFAULT NULL,
  `CHANGE_BY_USER_LOGIN_ID` varchar(250) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci DEFAULT NULL,
  `STATUS_ID` varchar(20) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci DEFAULT NULL,
  `LAST_UPDATED_STAMP` datetime(3) DEFAULT NULL,
  `LAST_UPDATED_TX_STAMP` datetime(3) DEFAULT NULL,
  `CREATED_STAMP` datetime(3) DEFAULT NULL,
  `CREATED_TX_STAMP` datetime(3) DEFAULT NULL,
  PRIMARY KEY (`EXAMPLE_ID`,`STATUS_DATE`),
  KEY `EXMPLST_EXMPL` (`EXAMPLE_ID`),
  KEY `EXMPLST_STTS` (`STATUS_ID`),
  KEY `EXMPLST_STTS_USER` (`CHANGE_BY_USER_LOGIN_ID`),
  KEY `EXMPL_STTS_TXSTMP` (`LAST_UPDATED_TX_STAMP`),
  KEY `EXMPL_STTS_TXCRTS` (`CREATED_TX_STAMP`),
  CONSTRAINT `EXMPLST_EXMPL` FOREIGN KEY (`EXAMPLE_ID`) REFERENCES `example` (`EXAMPLE_ID`),
  CONSTRAINT `EXMPLST_STTS` FOREIGN KEY (`STATUS_ID`) REFERENCES `status_item` (`STATUS_ID`),
  CONSTRAINT `EXMPLST_STTS_USER` FOREIGN KEY (`CHANGE_BY_USER_LOGIN_ID`) REFERENCES `user_login` (`USER_LOGIN_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3;

CREATE TABLE `example_type` (
  `EXAMPLE_TYPE_ID` varchar(20) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci NOT NULL,
  `PARENT_TYPE_ID` varchar(20) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci DEFAULT NULL,
  `DESCRIPTION` varchar(255) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci DEFAULT NULL,
  `LAST_UPDATED_STAMP` datetime(3) DEFAULT NULL,
  `LAST_UPDATED_TX_STAMP` datetime(3) DEFAULT NULL,
  `CREATED_STAMP` datetime(3) DEFAULT NULL,
  `CREATED_TX_STAMP` datetime(3) DEFAULT NULL,
  PRIMARY KEY (`EXAMPLE_TYPE_ID`),
  KEY `EXMPLTP_PAR` (`PARENT_TYPE_ID`),
  KEY `EXMPL_TP_TXSTMP` (`LAST_UPDATED_TX_STAMP`),
  KEY `EXMPL_TP_TXCRTS` (`CREATED_TX_STAMP`),
  CONSTRAINT `EXMPLTP_PAR` FOREIGN KEY (`PARENT_TYPE_ID`) REFERENCES `example_type` (`EXAMPLE_TYPE_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3;

CREATE TABLE `example_feature` (
  `EXAMPLE_FEATURE_ID` varchar(20) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci NOT NULL,
  `FEATURE_SOURCE_ENUM_ID` varchar(20) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci DEFAULT NULL,
  `DESCRIPTION` varchar(255) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci DEFAULT NULL,
  `LAST_UPDATED_STAMP` datetime(3) DEFAULT NULL,
  `LAST_UPDATED_TX_STAMP` datetime(3) DEFAULT NULL,
  `CREATED_STAMP` datetime(3) DEFAULT NULL,
  `CREATED_TX_STAMP` datetime(3) DEFAULT NULL,
  PRIMARY KEY (`EXAMPLE_FEATURE_ID`),
  KEY `EXFT_ENUM` (`FEATURE_SOURCE_ENUM_ID`),
  KEY `EXMPL_FTR_TXSTMP` (`LAST_UPDATED_TX_STAMP`),
  KEY `EXMPL_FTR_TXCRTS` (`CREATED_TX_STAMP`),
  CONSTRAINT `EXFT_ENUM` FOREIGN KEY (`FEATURE_SOURCE_ENUM_ID`) REFERENCES `enumeration` (`ENUM_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3;

CREATE TABLE `example_feature_appl` (
  `EXAMPLE_ID` varchar(20) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci NOT NULL,
  `EXAMPLE_FEATURE_ID` varchar(20) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci NOT NULL,
  `FROM_DATE` datetime(3) NOT NULL,
  `THRU_DATE` datetime(3) DEFAULT NULL,
  `EXAMPLE_FEATURE_APPL_TYPE_ID` varchar(20) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci DEFAULT NULL,
  `SEQUENCE_NUM` decimal(20,0) DEFAULT NULL,
  `LAST_UPDATED_STAMP` datetime(3) DEFAULT NULL,
  `LAST_UPDATED_TX_STAMP` datetime(3) DEFAULT NULL,
  `CREATED_STAMP` datetime(3) DEFAULT NULL,
  `CREATED_TX_STAMP` datetime(3) DEFAULT NULL,
  PRIMARY KEY (`EXAMPLE_ID`,`EXAMPLE_FEATURE_ID`,`FROM_DATE`),
  KEY `EXFTAP_EXPL` (`EXAMPLE_ID`),
  KEY `EXFTAP_EXFT` (`EXAMPLE_FEATURE_ID`),
  KEY `EXFTAP_TYP` (`EXAMPLE_FEATURE_APPL_TYPE_ID`),
  KEY `EXML_FTR_APL_TXSTP` (`LAST_UPDATED_TX_STAMP`),
  KEY `EXML_FTR_APL_TXCRS` (`CREATED_TX_STAMP`),
  CONSTRAINT `EXFTAP_EXFT` FOREIGN KEY (`EXAMPLE_FEATURE_ID`) REFERENCES `example_feature` (`EXAMPLE_FEATURE_ID`),
  CONSTRAINT `EXFTAP_EXPL` FOREIGN KEY (`EXAMPLE_ID`) REFERENCES `example` (`EXAMPLE_ID`),
  CONSTRAINT `EXFTAP_TYP` FOREIGN KEY (`EXAMPLE_FEATURE_APPL_TYPE_ID`) REFERENCES `example_feature_appl_type` (`EXAMPLE_FEATURE_APPL_TYPE_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3;

CREATE TABLE `example_feature_appl_type` (
  `EXAMPLE_FEATURE_APPL_TYPE_ID` varchar(20) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci NOT NULL,
  `PARENT_TYPE_ID` varchar(20) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci DEFAULT NULL,
  `DESCRIPTION` varchar(255) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci DEFAULT NULL,
  `LAST_UPDATED_STAMP` datetime(3) DEFAULT NULL,
  `LAST_UPDATED_TX_STAMP` datetime(3) DEFAULT NULL,
  `CREATED_STAMP` datetime(3) DEFAULT NULL,
  `CREATED_TX_STAMP` datetime(3) DEFAULT NULL,
  PRIMARY KEY (`EXAMPLE_FEATURE_APPL_TYPE_ID`),
  KEY `EXFTAPTP_PAR` (`PARENT_TYPE_ID`),
  KEY `EXL_FTR_APL_TP_TXP` (`LAST_UPDATED_TX_STAMP`),
  KEY `EXL_FTR_APL_TP_TXS` (`CREATED_TX_STAMP`),
  CONSTRAINT `EXFTAPTP_PAR` FOREIGN KEY (`PARENT_TYPE_ID`) REFERENCES `example_feature_appl_type` (`EXAMPLE_FEATURE_APPL_TYPE_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3;

SET FOREIGN_KEY_CHECKS=1;
